name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/cache@v4
        id: cache-game-libs
        with:
          path: 'C:/Program Files (x86)/Steam/steamapps/common/7 Days to Die Dedicated Server/7DaysToDieServer_Data/Managed'
          key: cache-1_2-b27

      - name: Setup steamcmd
        if: steps.cache-game-libs.outputs.cache-hit != 'true'
        uses: CyberAndrii/setup-steamcmd@v1.2.0

      - name: Update 7DTD
        if: steps.cache-game-libs.outputs.cache-hit != 'true'
        run: steamcmd +login anonymous +app_update 294420 +quit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build with MSBuild
        run: msbuild MVirus.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MVirus
          path: ./out/TN_MVirus
